repos:
    # Check that the commit message adheres to the Angular convention (this is needed so that Semantic Release works)
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.20.4
      hooks:
          - id: commitizen
            stages: [commit-msg]
    # Fixes the spaces
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    # Black formats the Python code
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
    # # Flake8 lints the Python code
    # - repo: https://github.com/pycqa/flake8
    #   rev: 4.0.1
    #   hooks:
    #       - id: flake8
    # Isort sorts the imports
    - repo: https://github.com/pycqa/isort
      rev: 5.5.2
      hooks:
        - id: isort
